/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Dates transform
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AuctionDetails } from './model';

import { customInstance } from '../../../mutators/custom-instance';
const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getAuctionDetails = (auctionId: string, signal?: AbortSignal) => {
  return customInstance<AuctionDetails>({
    url: `/auctions/${auctionId}`,
    method: 'GET',
    signal,
  }).then(deserializeGetAuctionDetailsResponse);
};

const deserializeGetAuctionDetailsResponse = (
  data: AuctionDetails,
): AuctionDetails => {
  if (data == null) return data;
  data.startTime = new Date(data.startTime);
  if (data.endTime != null) {
    data.endTime = new Date(data.endTime);
  }
  for (let i0 = 0; i0 < data.log.length; i0++) {
    data.log[i0].createdAt = new Date(data.log[i0].createdAt);
  }
  return data;
};

export const getGetAuctionDetailsQueryKey = (auctionId: string) => {
  return [`/auctions/${auctionId}`] as const;
};

export const getGetAuctionDetailsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuctionDetails>>,
  TError = unknown,
>(
  auctionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuctionDetails>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuctionDetailsQueryKey(auctionId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAuctionDetails>>
  > = ({ signal }) => getAuctionDetails(auctionId, signal);

  return {
    queryKey,
    queryFn,
    enabled: auctionId !== null && auctionId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuctionDetails>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuctionDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuctionDetails>>
>;
export type GetAuctionDetailsQueryError = unknown;

export function useGetAuctionDetails<
  TData = Awaited<ReturnType<typeof getAuctionDetails>>,
  TError = unknown,
>(
  auctionId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuctionDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuctionDetails>>,
          TError,
          Awaited<ReturnType<typeof getAuctionDetails>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuctionDetails<
  TData = Awaited<ReturnType<typeof getAuctionDetails>>,
  TError = unknown,
>(
  auctionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuctionDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuctionDetails>>,
          TError,
          Awaited<ReturnType<typeof getAuctionDetails>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuctionDetails<
  TData = Awaited<ReturnType<typeof getAuctionDetails>>,
  TError = unknown,
>(
  auctionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuctionDetails>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAuctionDetails<
  TData = Awaited<ReturnType<typeof getAuctionDetails>>,
  TError = unknown,
>(
  auctionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuctionDetails>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAuctionDetailsQueryOptions(auctionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const listAuctionNames = (signal?: AbortSignal) => {
  return customInstance<string[]>({ url: `/auctions`, method: 'GET', signal });
};

export const getListAuctionNamesQueryKey = () => {
  return [`/auctions`] as const;
};

export const getListAuctionNamesQueryOptions = <
  TData = Awaited<ReturnType<typeof listAuctionNames>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listAuctionNames>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAuctionNamesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAuctionNames>>
  > = ({ signal }) => listAuctionNames(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAuctionNames>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAuctionNamesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAuctionNames>>
>;
export type ListAuctionNamesQueryError = unknown;

export function useListAuctionNames<
  TData = Awaited<ReturnType<typeof listAuctionNames>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAuctionNames>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAuctionNames>>,
          TError,
          Awaited<ReturnType<typeof listAuctionNames>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAuctionNames<
  TData = Awaited<ReturnType<typeof listAuctionNames>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAuctionNames>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAuctionNames>>,
          TError,
          Awaited<ReturnType<typeof listAuctionNames>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAuctionNames<
  TData = Awaited<ReturnType<typeof listAuctionNames>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAuctionNames>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListAuctionNames<
  TData = Awaited<ReturnType<typeof listAuctionNames>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAuctionNames>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListAuctionNamesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
