/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Dates transform
 * OpenAPI spec version: 1.0.0
 */
import type { LogEvent } from './logEvent';

export interface AuctionDetails {
  startTime: Date;
  /** @nullable */
  endTime?: Date | null;
  name?: string;
  log: LogEvent[];
}
