/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Dates transform
 * OpenAPI spec version: 1.0.0
 */

export type DutchAuctionSummaryAuctionType =
  (typeof DutchAuctionSummaryAuctionType)[keyof typeof DutchAuctionSummaryAuctionType];

export const DutchAuctionSummaryAuctionType = {
  dutch: 'dutch',
} as const;
