/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Dates transform
 * OpenAPI spec version: 1.0.0
 */
import type { EnglishAuctionSummaryAuctionType } from './englishAuctionSummaryAuctionType';

export interface EnglishAuctionSummary {
  auctionType: EnglishAuctionSummaryAuctionType;
  startTime: Date;
}
