/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Dates transform
 * OpenAPI spec version: 1.0.0
 */

export type EnglishAuctionSummaryAuctionType =
  (typeof EnglishAuctionSummaryAuctionType)[keyof typeof EnglishAuctionSummaryAuctionType];

export const EnglishAuctionSummaryAuctionType = {
  english: 'english',
} as const;
