/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Dates transform
 * OpenAPI spec version: 1.0.0
 */

export interface LogEvent {
  createdAt: Date;
  resolvedAt?: Date;
  message?: string;
}
